spring:
  datasource:
    url: jdbc:postgresql://dsp-postgresql:5432/dsp # for postgresql and springboot service in docker container
    #url: jdbc:postgresql://localhost:5432/dsp # postgresql or springboot service in local
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  expiration: 60000
  algorithm: RS256